- frontend/src/components/PostEditor.vue
- frontend/src/views/NewPostPageView.vue
> feat: vditor add loading

- frontend_nuxt/app.vue
- frontend_nuxt/components/HeaderComponent.vue
- frontend_nuxt/components/MenuComponent.vue
- frontend_nuxt/nuxt.config.ts
- frontend_nuxt/pages/index.vue
- frontend_nuxt/pages/posts/[id]/index.vue
- frontend_nuxt/pages/users/[id].vue
- frontend_nuxt/plugins/ldrs.client.ts
- frontend_nuxt/plugins/nprogress.client.ts
- frontend_nuxt/plugins/theme.client.ts
- frontend_nuxt/plugins/toastification.client.ts
- frontend_nuxt/utils/markdown.js
有以下warn
- markdowan解析水合warn
- 原生组件(web components)vue解析warn
- Nuxt编译宏需要放在Setup的Warn
> fix: 清理掉了大部分warn，优化了在移动端侧边栏的逻辑问题

- frontend_nuxt/utils/markdown.js
> fix:外链新窗口跳转 #509

- frontend_nuxt/components/DropdownMenu.vue
- frontend_nuxt/pages/forgot-password.vue
> feat: 忘记密码页面添加提示 & 修复缺少定义导致的报错 #535

- frontend_nuxt/app.vue
- frontend_nuxt/components/HeaderComponent.vue
- frontend_nuxt/components/MenuComponent.vue
- frontend_nuxt/components/ToolTip.vue
- frontend_nuxt/pages/index.vue
> refactor: 在 header 组件中添加发帖功能，移动端添加发帖悬浮按钮，优化首页搜索标题样式 , 

- frontend_nuxt/app.vue
- frontend_nuxt/components/HeaderComponent.vue
- frontend_nuxt/components/MenuComponent.vue
- frontend_nuxt/nuxt.config.ts
- frontend_nuxt/utils/theme.js
fix #582   
fix #585 
**ios chrome 浏览器未解决！！！！**
> fix: 手机状态栏暗黑模式背景颜色显示不正确

- frontend_nuxt/utils/theme.js
- Unified coordinate handling for mouse and touch events to ensure the animation start point accurately follows the finger position on mobile devices.
> fix: incorrect animation start position on mobile theme toggle

- frontend_nuxt/app.vue
- frontend_nuxt/components/DropdownMenu.vue
- frontend_nuxt/nuxt.config.ts
- Add page transition CSS with opacity and blur effects
- Wrap dropdown in Transition component with slide effect
- Configure Nuxt pageTransition in config
> feat: add transition effects for page and dropdown

- frontend_nuxt/pages/index.vue
- frontend_nuxt/pages/message.vue
- frontend_nuxt/pages/posts/[id]/index.vue
> fix: 修复我的信息界面中的header无法粘性布局的bug以及解决了一些-webkit样式警告

- frontend_nuxt/pages/index.vue
> fix: 帖子描述与参与人员重叠

- frontend_nuxt/components/ReactionsGroup.vue
- frontend_nuxt/composables/useReactionTypes.js
- frontend_nuxt/pages/posts/[id]/index.vue
> 修复文章详情页面返回后不更新数据 & 优化 /reaction-types 接口重复调用

- frontend_nuxt/components/MessageFloatWindow.vue
`iframe`中注入`<base target="_top">`
Closed #723
> fix: 修复小窗口点击站内链接，会从小窗直接跳，预期主窗口跳转 #723

- frontend_nuxt/pages/message-box/[id].vue
> fix: 站内信 scroll问题 #749

- backend/src/main/java/com/openisle/model/Draft.java
- backend/src/main/java/com/openisle/model/Post.java
> 解决文章和草稿长度不够的问题

- frontend_nuxt/assets/global.css
> fix: markdown引用ui修改 #837

- backend/pom.xml
- backend/src/main/java/com/openisle/config/CachingConfig.java
- backend/src/main/java/com/openisle/config/RedisConnectionLogger.java
- backend/src/main/java/com/openisle/model/Tag.java
- backend/src/main/java/com/openisle/service/CategoryService.java
- backend/src/main/java/com/openisle/service/TagService.java
- backend/src/main/resources/application.properties
- backend/src/main/resources/db/init/init_script.sql
本次主要改动范围：
1.分类列表缓存
2.标签列表缓存
追加的新类库
1.redis
2.jsr310→java8时间类localdatetime无法解析的问题
3.jaskson-hibernate6->hibernate 字段懒加载问题
其他改动
1.修改了初始化脚本的用户名，追加密码说明
> 轻量级redis缓存追加

- frontend_nuxt/components/ArticleCategory.vue
- frontend_nuxt/components/ArticleTags.vue
- frontend_nuxt/components/MenuComponent.vue
- frontend_nuxt/plugins/iconpark.client.ts
> feat: 侧边栏按钮样式逻辑修改

- frontend_nuxt/assets/global.css
- frontend_nuxt/components/PostChangeLogItem.vue
> fix: changelog--文章内容更新 移动端适配 #937

- frontend_nuxt/components/MenuComponent.vue
- frontend_nuxt/composables/postFilter.ts
- frontend_nuxt/pages/index.vue
> menu追加选中状态

- frontend_nuxt/assets/global.css
- frontend_nuxt/components/CommentEditor.vue
- frontend_nuxt/components/MessageEditor.vue
- frontend_nuxt/pages/login.vue
- frontend_nuxt/pages/new-post.vue
- frontend_nuxt/pages/posts/[id]/edit.vue
- frontend_nuxt/pages/signup.vue
> fix: loading icon

- frontend_nuxt/pages/index.vue
> fix: 移动端头像显示问题 #1023

- frontend_nuxt/pages/users/[id].vue
> 修改主页各section间距
